### ISSUE TITLE
Directions for use?

### ISSUE THREAD

**Issue by roberttolton** [esbenp/fineuploader-server#4]
Looks like a good package to get running with fineuploader, though how do you use it..?

**Comment by rygos** [comment]
This is the question.
I tryed around a bit and i think the following steps are a good starting point:
- composer require optimus/fineupload-server
- Register Service Provider in app.php: "Optimus\FineuploaderServer\Provider\LaravelServiceProvider::class,"
- php artisan vendor:publish
- for blade templates use the documentation from fineuploader.com
- create a new controller and create a post route to the following function in this controller
- ``` php
  public function endpoint(Request $request){
      $fu = new FineUploader();
      $res = $fu->handleUpload(storage_path('app/public/temp'),'file');
  
      return json_encode($res);
  }
  ```

```
* in your template point the endpoints to the created route.

Now your files are uploaded. If i figured out some other things, i write them down here.
```

**Comment by esbenp** [comment]
Hey guys sorry for inactivity. Here are some basic instructions. I do not know if they are adequate but hopefully it will provide for a start. https://github.com/esbenp/fineuploader-server/blob/master/README.md

**Comment by mblarsen** [comment]
@esbenp is chunks.concurrent.enabled = true supported? If so what should the endpoint be?
